import type { Mission, MissionTask } from "@/content/schemas/mission";

type MissionSeed = Omit<Mission, "tasks"> & {
  question: string;
  options: string[];
  answer: number;
  correct: string;
  incorrect: string;
};

function mission(seed: MissionSeed): Mission {
  const rotation = seed.chapter % seed.options.length;
  const options = [...seed.options.slice(rotation), ...seed.options.slice(0, rotation)];
  const correctOption = seed.options[seed.answer];
  const task: MissionTask = {
    id: `${seed.id}-practice`,
    type: seed.externalAction ? "checklist" : "simulator",
    prompt: seed.question,
    options,
    correctIndex: options.indexOf(correctOption),
    correctFeedback: seed.correct,
    incorrectFeedback: seed.incorrect,
    termIds: seed.termIds,
  };
  return {
    id: seed.id,
    chapter: seed.chapter,
    phase: seed.phase,
    title: seed.title,
    shortTitle: seed.shortTitle,
    summary: seed.summary,
    story: seed.story,
    objectives: seed.objectives,
    termIds: seed.termIds,
    uiTerms: seed.uiTerms,
    completionMessage: seed.completionMessage,
    externalAction: seed.externalAction,
    verificationMode: seed.verificationMode,
    tasks: [task],
  };
}

export const missions: Mission[] = [
  mission({
    id: "chapter-0", chapter: 0, phase: 1, title: "找到并进入仓库", shortTitle: "村口路标",
    summary: "在真实 GitHub 仓库页找到 README、Fork 和 Code，并理解它们各自负责什么。",
    story: "你站在新手村入口。第一项能力不是点进游戏，而是看懂承载游戏的真实仓库。",
    objectives: ["识别仓库页面", "找到中文入口", "区分收藏与复制"],
    termIds: ["repository", "readme", "fork", "code-tab", "code-menu", "public", "star"],
    uiTerms: ["Repository", "README", "Fork", "Code", "Public", "Star"],
    question: "你想把项目复制到自己的 GitHub 账号中，下一步应选择什么？",
    options: ["Fork", "Star", "只打开 README"], answer: 0,
    correct: "正确。Fork 会在你的账号下创建有关联的仓库副本，Star 只是可选收藏。",
    incorrect: "再想想：收藏和阅读都不会在你的账号下创建仓库副本。",
    completionMessage: "你已经读懂村口路标，可以进入真实 GitHub 流程。",
    externalAction: true, verificationMode: "self-check",
  }),
  mission({
    id: "chapter-1", chapter: 1, phase: 1, title: "注册、登录与账号安全", shortTitle: "守门人的钥匙",
    summary: "只在 GitHub 官方页面注册或登录，认识 2FA、Passkey 和 Recovery codes。",
    story: "守门人不会索要你的密码。他只提醒你确认地址栏并保护好恢复方式。",
    objectives: ["区分注册与登录", "知道凭据只交给 GitHub", "保存恢复方式"],
    termIds: ["sign-up", "sign-in", "two-factor-authentication", "passkey", "recovery-codes", "username", "profile", "settings"],
    uiTerms: ["Sign up", "Sign in", "Username", "Profile", "Settings", "Two-factor authentication", "Passkey", "Recovery codes"],
    question: "教程页面要求你粘贴 Recovery codes 才能继续。你应该怎么做？",
    options: ["拒绝并关闭页面，只在 GitHub 官方设置中管理恢复代码", "粘贴一个没用过的代码", "截图发给维护者"], answer: 0,
    correct: "正确。恢复代码属于敏感凭据，本项目永远不会收集它。",
    incorrect: "危险：Recovery codes 可用于恢复账号，不应交给教程、维护者或陌生页面。",
    completionMessage: "账号安全边界清楚了。真正的登录永远发生在 GitHub 官方页面。",
    externalAction: true, verificationMode: "self-check",
  }),
  mission({
    id: "chapter-2", chapter: 2, phase: 1, title: "真正复制项目", shortTitle: "三条下山路",
    summary: "选择 GitHub Desktop、命令行或 Codespaces，理解 Fork、Clone 与 ZIP 的差异。",
    story: "你已经拥有自己的 Fork。现在需要选择一条路线，把完整项目带到可工作的环境。",
    objectives: ["推荐 Desktop 路线", "理解 HTTPS Clone", "知道 ZIP 的限制"],
    termIds: ["fork", "clone", "download-zip", "codespaces", "code-menu"],
    uiTerms: ["Fork", "Clone", "Download ZIP", "Codespaces", "Code"],
    question: "你希望学习 Commit、Push 和同步远程仓库，应优先选择哪种获取方式？",
    options: ["Clone 自己的 Fork", "Download ZIP", "只 Star 原仓库"], answer: 0,
    correct: "正确。Clone 会保留 Git 历史和远程关系，适合完整学习流程。",
    incorrect: "Download ZIP 只有当前文件快照，Star 只是收藏，都不能替代 Clone。",
    completionMessage: "你已经能为不同场景选择正确的复制方式。",
    externalAction: true, verificationMode: "self-check",
  }),
  mission({
    id: "chapter-3", chapter: 3, phase: 1, title: "在本地运行游戏", shortTitle: "点亮营火",
    summary: "安装 Node.js，用 npm 安装依赖并启动 localhost 开发服务器。",
    story: "项目已经来到电脑上。接下来不是背命令，而是理解每条命令改变了什么。",
    objectives: ["确认 Node.js 版本", "安装依赖", "启动和停止服务器"],
    termIds: ["nodejs", "npm-install", "npm-run-dev", "localhost"],
    uiTerms: ["Node.js", "npm install", "npm run dev", "localhost"],
    question: "第一次 Clone 后，`npm run dev` 提示找不到依赖。通常先做什么？",
    options: ["在项目目录执行 npm install", "把 GitHub 密码输进终端", "删除 package.json"], answer: 0,
    correct: "正确。npm install 会根据项目清单安装本地运行所需依赖。",
    incorrect: "不要输入 GitHub 密码或删除项目清单。先确认目录，再执行 npm install。",
    completionMessage: "营火点亮了。你已经知道项目从文件变成网页的过程。",
    externalAction: true, verificationMode: "self-check",
  }),
  mission({
    id: "chapter-4", chapter: 4, phase: 2, title: "仓库地图", shortTitle: "仓库瞭望塔",
    summary: "探索原创仓库 nightwalk-map，读懂文件、分支、历史、参与者、许可和版本入口。",
    story: "NPC 维护者林澈递给你一张地图：先确认仓库归属、默认分支和使用许可。",
    objectives: ["定位默认分支", "找到版本历史", "判断仓库许可"],
    termIds: ["repository", "readme", "branch", "main", "license", "code-tab", "public", "private", "owner", "contributors", "releases", "tag"],
    uiTerms: ["Code", "Branch", "main", "Contributors", "License", "Releases", "Tags", "Public", "Private"],
    question: "你想知道这段代码能否合法复用，最应该先打开哪个文件？",
    options: ["LICENSE", "README 中的截图", "Contributors"], answer: 0,
    correct: "正确。LICENSE 明确授权范围和条件，不能只凭仓库公开就假设可任意使用。",
    incorrect: "Public 代表可见，不自动等于可任意复制、修改和分发。查看 LICENSE。",
    completionMessage: "你能从仓库地图中找到使用项目所需的关键证据。",
    externalAction: false, verificationMode: "game",
  }),
  mission({
    id: "chapter-5", chapter: 5, phase: 2, title: "寻找和判断开源项目", shortTitle: "集市鉴宝",
    summary: "从文档、更新、发布、许可和归档状态判断一个项目是否适合使用。",
    story: "集市里最亮的摊位不一定最可靠。你需要用多项证据判断项目健康度。",
    objectives: ["不只看 Star", "查安装与要求", "检查维护状态"],
    termIds: ["search", "readme", "license", "releases", "archived", "contributing", "installation", "requirements"],
    uiTerms: ["Search", "README", "Installation", "Requirements", "License", "Releases", "Archived", "CONTRIBUTING"],
    question: "一个项目 Star 很多，但已 Archived 且没有 License。最稳妥的判断是什么？",
    options: ["先不要直接用于正式项目，继续查替代方案和授权", "Star 多就一定安全", "公开可见就能任意商用"], answer: 0,
    correct: "正确。热度不是维护与授权的替代证据。",
    incorrect: "Star 不能证明仍在维护，也不能替代 License 的授权。",
    completionMessage: "你学会了用证据选择项目，不再只看热度。",
    externalAction: false, verificationMode: "game",
  }),
  mission({
    id: "chapter-6", chapter: 6, phase: 2, title: "关注项目", shortTitle: "消息驿站",
    summary: "通过场景区分 Star、Watch、Notifications、Follow 和 Fork。",
    story: "驿站每天送来很多消息。你要选择恰当的关注方式，避免通知淹没重要工作。",
    objectives: ["收藏仓库", "订阅仓库通知", "关注用户"],
    termIds: ["star", "watch", "notifications", "follow", "fork"],
    uiTerms: ["Star", "Watch", "Notifications", "Follow", "Fork"],
    question: "你只想以后容易找到项目，不想收到每次 Issue 更新。选择什么？",
    options: ["Star", "Watch all activity", "Fork 并开启全部通知"], answer: 0,
    correct: "正确。Star 适合收藏，且它是完全可选的，不是通关条件。",
    incorrect: "Watch 主要控制通知，Fork 用于创建仓库副本。仅收藏请选择 Star。",
    completionMessage: "你能按目标管理收藏、通知、用户关注和副本。",
    externalAction: false, verificationMode: "game",
  }),
  mission({
    id: "chapter-7", chapter: 7, phase: 3, title: "Issue 和任务管理", shortTitle: "夜游地图报错",
    summary: "在虚构项目中记录 README 路线错误，认识状态、标签、负责人和讨论。",
    story: "你发现 nightwalk-map 的 README 把南门写成北门。先记录问题，再开始改代码。",
    objectives: ["区分问题与改动", "描述可复现问题", "理解分类和负责人"],
    termIds: ["issue", "open", "closed", "label", "assignee", "comment", "notifications", "milestone", "good-first-issue", "subscribe"],
    uiTerms: ["Issue", "Open", "Closed", "Label", "Assignee", "Milestone", "Comment", "Subscribe", "good first issue"],
    question: "你只是发现 README 有错误，还没有修改文件。应先创建什么？",
    options: ["Issue", "Pull Request", "Release"], answer: 0,
    correct: "正确。Issue 可先记录问题；Pull Request 应包含具体变更提案。",
    incorrect: "还没有变更时，先用 Issue 清楚记录问题和证据。",
    completionMessage: "Issue #18 已在剧情仓库中记录。游戏按钮只是模拟，不会写入 GitHub。",
    externalAction: false, verificationMode: "game",
  }),
  mission({
    id: "chapter-8", chapter: 8, phase: 3, title: "本地与远程", shortTitle: "双城信使",
    summary: "建立本地、origin 和 upstream 的心智模型，区分 Fetch、Pull、Push 与 Sync fork。",
    story: "一份仓库在电脑上，一份在你的 GitHub，一份在原作者账号下。信使路线不能走反。",
    objectives: ["区分本地与远程", "理解远程简称", "选择正确同步动作"],
    termIds: ["local-repository", "remote-repository", "origin", "upstream", "fetch", "pull", "push", "working-directory", "sync-fork"],
    uiTerms: ["Local repository", "Remote repository", "origin", "upstream", "Fetch", "Pull", "Push", "Sync fork", "Working directory"],
    question: "你只想先知道远程有没有新提交，不想立刻合入当前分支，应使用什么？",
    options: ["Fetch", "Pull", "Push"], answer: 0,
    correct: "正确。Fetch 获取远程信息但不自动整合，适合先查看。",
    incorrect: "Pull 会获取并整合，Push 的方向是本地到远程。先查看应选 Fetch。",
    completionMessage: "你已经能说清每条同步路线的方向。",
    externalAction: false, verificationMode: "game",
  }),
  mission({
    id: "chapter-9", chapter: 9, phase: 3, title: "Branch、修改和 Commit", shortTitle: "修好南门路标",
    summary: "创建分支、修改 README、检查 Diff、Stage、Commit 并 Push。",
    story: "你在 fix/south-gate 分支把错误路线改正。提交前需要检查只改了该改的内容。",
    objectives: ["隔离修改", "检查差异", "写清提交说明"],
    termIds: ["branch", "main", "working-directory", "diff", "stage", "commit", "push", "sha", "changes", "commit-message"],
    uiTerms: ["Branch", "main", "Changes", "Diff", "Stage", "Commit", "Commit message", "SHA", "Push"],
    question: "文件改好后，正确的顺序是哪一个？",
    options: ["检查 Diff → Stage → Commit → Push", "Push → Stage → Commit", "Merge → Clone → Commit"], answer: 0,
    correct: "正确。先检查，再选择进入提交的修改，保存提交后推送到远程分支。",
    incorrect: "Commit 只保存已暂存的修改，Push 只发送已有提交。顺序不能倒置。",
    completionMessage: "修复已经作为清晰的提交出现在远程分支。",
    externalAction: false, verificationMode: "game",
  }),
  mission({
    id: "chapter-10", chapter: 10, phase: 3, title: "Pull Request", shortTitle: "提出合并提案",
    summary: "选择正确 Base 与 Compare，理解 Draft、Conversation、Commits、Checks 和 Files changed。",
    story: "修改已经推送。现在你要邀请维护者审查，而不是让 GitHub 把别人的代码拉到你电脑。",
    objectives: ["理解合并提案", "确认分支方向", "检查完整变更"],
    termIds: ["pull-request", "pull", "open", "closed", "diff", "checks", "draft", "files-changed", "new-pull-request", "base-branch", "compare-branch", "conversation", "commits-tab"],
    uiTerms: ["Pull Request", "New pull request", "Base branch", "Compare branch", "Draft", "Conversation", "Commits", "Checks", "Files changed"],
    question: "你要把 fix/south-gate 的修改提议合入 main，方向应怎样设置？",
    options: ["base: main，compare: fix/south-gate", "base: fix/south-gate，compare: main", "两个都选 main"], answer: 0,
    correct: "正确。Base 是接收变更的目标，Compare 是提供变更的来源。",
    incorrect: "把 Pull Request 理解为合并提案：Compare 的变化准备进入 Base。",
    completionMessage: "PR #19 已在剧情中打开。它是一份可讨论的变更提案。",
    externalAction: false, verificationMode: "game",
  }),
  mission({
    id: "chapter-11", chapter: 11, phase: 3, title: "Review 与 Merge", shortTitle: "维护者的回信",
    summary: "处理评论与修改要求，理解批准、冲突和三种常见合并方式。",
    story: "维护者林澈要求补充一个标点。你更新提交后，检查通过，审查也被批准。",
    objectives: ["区分评论与审查结论", "回应修改要求", "理解冲突风险"],
    termIds: ["review", "comment", "approve", "request-changes", "merge", "merge-conflict", "squash-merge", "rebase-merge", "resolve-conversation"],
    uiTerms: ["Review", "Comment", "Approve", "Request changes", "Resolve conversation", "Merge", "Squash and merge", "Rebase and merge", "Merge conflict"],
    question: "审查者只留下 Comment，没有选择 Approve。这代表什么？",
    options: ["提供了反馈，但不等于已批准", "一定可以直接 Merge", "Pull Request 已关闭"], answer: 0,
    correct: "正确。Comment 是反馈；Approve 和 Request changes 才是明确审查结论。",
    incorrect: "评论不自动代表批准，也不会自动关闭 Pull Request。",
    completionMessage: "你已理解审查结论和合并选择，不会把自动操作当作无风险覆盖。",
    externalAction: false, verificationMode: "game",
  }),
  mission({
    id: "chapter-12", chapter: 12, phase: 3, title: "Actions、Checks 与 Release", shortTitle: "自动检查工坊",
    summary: "观察提交触发 Workflow，经 Job 和 Step 产生 Checks，再理解 Tag 与 Release。",
    story: "工坊自动安装依赖、检查内容、运行测试。绿灯是证据之一，不是魔法保证。",
    objectives: ["读懂自动化层级", "查看失败日志", "区分标签与发行版"],
    termIds: ["actions", "workflow", "workflow-run", "checks", "releases", "release", "tag", "job", "step", "passed", "failed", "artifact", "changelog", "github-pages"],
    uiTerms: ["Actions", "Workflow", "Workflow run", "Job", "Step", "Checks", "Passed", "Failed", "Artifact", "Release", "Tag", "Changelog", "GitHub Pages"],
    question: "Checks 显示 Failed，最合理的下一步是什么？",
    options: ["打开失败的 Job 和 Step 查看日志", "忽略并假设代码没问题", "删除整个仓库"], answer: 0,
    correct: "正确。沿 Workflow run → Job → Step 查看失败位置和日志。",
    incorrect: "失败状态需要证据驱动排查，既不能盲目忽略，也不需要删除仓库。",
    completionMessage: "自动检查通过后，nightwalk-map 准备发布一个新的 Release。",
    externalAction: false, verificationMode: "game",
  }),
  mission({
    id: "chapter-13", chapter: 13, phase: 3, title: "健康的开源项目", shortTitle: "村庄公约",
    summary: "阅读贡献、许可、行为和安全文件，认识维护者、贡献者与社区空间。",
    story: "代码不是开源社区的全部。清楚的规则让陌生人能安全、高效地一起工作。",
    objectives: ["找到贡献规则", "私下报告漏洞", "理解社区角色"],
    termIds: ["license", "contributors", "contributor", "contributing", "code-of-conduct", "security-policy", "discussions", "wiki", "maintainer", "collaborator", "community-standards"],
    uiTerms: ["CONTRIBUTING", "LICENSE", "CODE_OF_CONDUCT", "SECURITY", "Discussions", "Wiki", "Maintainer", "Contributor", "Collaborator", "Community standards"],
    question: "你发现可能泄露用户数据的安全漏洞，应该先怎么做？",
    options: ["按 SECURITY 指定方式私下报告", "公开发 Issue 附上完整利用步骤", "发到无关项目的 Discussion"], answer: 0,
    correct: "正确。安全漏洞应按项目 SECURITY 政策私下报告，避免扩大风险。",
    incorrect: "未修复漏洞不应先公开扩散。查找 SECURITY 并按安全渠道报告。",
    completionMessage: "你已经理解一个健康开源项目不仅有代码，也有清楚的协作边界。",
    externalAction: false, verificationMode: "game",
  }),
];

export const missionsById = new Map(missions.map((item) => [item.id, item]));
