'use client';
import {useState} from 'react';
import {chapterScenes} from '@/content/scenarios/chapter-scenes';
import {campaignChapters,numerals,lastCampaignChapter} from '@/content/minigames/campaign';
import {earnedChapters,nextChapter,type WuxiaState,type WuxiaAction} from '@/core/game/wuxia';
import {PlacedCharacter} from './character-placement';
import {Act} from './campaign/shared';
import {innRules} from '@/content/minigames/inn';
import {SideQuest} from './campaign/sidequest';
export function JianghuMap({state,dispatch}:{state:WuxiaState;dispatch:React.Dispatch<WuxiaAction>}){
 const earned=earnedChapters(state),next=nextChapter(state),[selected,setSelected]=useState(next),[sidequestOpen,setSidequestOpen]=useState(false);const focus=chapterScenes[selected],target=chapterScenes[next];
 const sidequestUnlocked=earned.length>=innRules.unlockChapters;
 return <section className="campaign-map" aria-labelledby="jianghu-title"><header><div><small>山川为卷 · 循路求知</small><h1 id="jianghu-title">云溪谷</h1></div><p>已集 {earned.length} / {campaignChapters.length} 枚章印 · {state.wallet.copper} 文 · {state.wallet.silver} 两</p></header><div className="map-viewport"><div className="campaign-map-art"><div className="map-interior"><div className="map-landscape"/>{chapterScenes.map(scene=>{const locked=scene.chapter>next,completed=earned.includes(scene.chapter);return <div key={scene.chapter} className={`campaign-map-pin ${locked?'locked':completed?'complete':'available'} ${selected===scene.chapter?'selected':''}`} style={{left:`${scene.mapAnchor.x}%`,top:`${scene.mapAnchor.y}%`}}>{locked&&<span className="map-cloud" aria-hidden/>}<button aria-label={`第 ${scene.chapter} 章 ${scene.title}，${locked?'待解锁':completed?'已完成':'可进入'}`} aria-pressed={selected===scene.chapter} onClick={()=>setSelected(scene.chapter)} onDoubleClick={()=>!locked&&dispatch({type:'enter',chapter:scene.chapter})}><span className="map-scroll-sprite" style={{backgroundImage:`url(/assets/phase-c/nodes/chapter-${scene.chapter}.png)`,backgroundPosition:`${locked?0:completed?100:50}% 50%`}}/><span className="map-place-label">{scene.title}</span></button></div>;})}<div className="campaign-map-hero" style={{left:`${target.mapAnchor.x}%`,top:`${target.mapAnchor.y+6}%`}}><PlacedCharacter id={state.character!} pose="standing"/></div>{state.rewardFrom!==null&&state.rewardFrom<lastCampaignChapter&&<div key={state.rewardFrom} aria-hidden className="map-reveal-cloud" style={{left:`${target.mapAnchor.x-8}%`,top:`${target.mapAnchor.y-10}%`}}/>}<div className={`campaign-map-pin inn-map-pin ${sidequestUnlocked?'available':'locked'}`} style={{left:'84%',top:'78%'}}><button aria-label={`百戏客栈，${sidequestUnlocked?'可进入':'待解锁，可免费试桌'}`} onClick={()=>setSidequestOpen(true)}><span className="map-scroll-sprite inn-scroll" style={{backgroundImage:'url(/assets/phase-c/refined/inn-nodes.png)',backgroundPosition:sidequestUnlocked?'100% center':'0% center'}}/><span className="map-place-label">百戏客栈</span></button></div></div></div></div><div className="campaign-map-bottom"><div><strong>第{numerals[selected]}章 · {focus.title}</strong><p>{selected>next?`先完成第${numerals[selected-1]}章，取得通行凭证后道路显现。`:earned.includes(selected)?`${focus.returnMapReward.item} 已收进行囊；可重访练习新局面。`:'当前地点已经开放，带着上一章的线索前往。'}</p></div><SelectChapter value={selected} onChange={setSelected}/><Act disabled={selected>next} onClick={()=>dispatch({type:'enter',chapter:selected})}>{earned.includes(selected)?'重访此地':'前往此地'}</Act>{earned.length===campaignChapters.length&&<a className="campaign-action" href="#jianghu-ending">全线通关 · 留步饮茶</a>}</div>{sidequestOpen&&<SideQuest state={state} dispatch={dispatch} onClose={()=>setSidequestOpen(false)}/>}</section>;
}
function SelectChapter({value,onChange}:{value:number;onChange:(n:number)=>void}){return <label className="map-index-label">地点索引<select aria-label="主线地点索引" value={value} onChange={e=>onChange(Number(e.target.value))}>{chapterScenes.map(s=><option key={s.chapter} value={s.chapter}>第{numerals[s.chapter]}章 · {s.title}</option>)}</select></label>;}
