import { z } from "zod";
export const chainLessonSchema = z.object({ chapter: z.number().int().min(7).max(12), place: z.string(), title: z.string(), story: z.string(), objective: z.string(), sourceUrl: z.url(), lastVerifiedAt: z.string(), termIds: z.array(z.string()), notes: z.array(z.string()), commands: z.array(z.string()) });
export const contributionMissions = [
  { chapter: 7, place: "悬赏亭", title: "把问题写成一份委托", story: "青砚递来旅人手记：README 把安全入口南门写成了北门。先让维护者知道怎样复现，再动手修。", objective: "搜索已有议题；填写标题、实际与期望结果；由模拟维护者应用 bug 标签并创建 Issue #13。", termIds: ["issue", "open", "closed", "label", "assignee", "milestone", "good-first-issue"], sourceUrl: "https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/creating-an-issue", lastVerifiedAt: "2026-09-11", notes: ["Issue 是讨论与跟踪，不会修改 README。Open 是仍在处理；Closed 不一定意味着代码已经合并。", "bug 是缺陷，enhancement 是改进建议，duplicate 是与已有议题重复；Label 名称可由仓库定义。", "Assignee 是负责人，Milestone 是阶段目标。普通访客未必有权设置；本关标签由模拟维护者应用。", "good first issue 是适合新贡献者的常用标签，不是所有 Issue 都有‘领取任务’按钮。"], commands: [] },
  { chapter: 8, place: "双城驿站", title: "让提交抵达正确驿站", story: "上游修好了石桥，main 多了 u1。你的电脑与 Fork 还在 u0。先取信、整合，再送到自己的仓库。", objective: "将 upstream/main 的 u1 通过 Fetch、Pull、Push 带到本地和 origin，观察三个位置的差别。", termIds: ["local-repository", "remote-repository", "origin", "upstream", "fetch", "pull", "push", "sync-fork"], sourceUrl: "https://git-scm.com/docs/git-fetch", lastVerifiedAt: "2026-09-11", notes: ["origin、upstream 是远端别名，不是保留权限角色。本练习约定前者是自己的 Fork，后者是原项目。", "Fetch 获取对象、更新远端跟踪记录，不自动整合工作分支。Pull 会获取再整合。", "Push 发送已提交历史到有权限的远端，不能上传尚未提交的工作区。", "网页 Sync fork 更新 GitHub 上的 Fork，不顺便更新电脑。Desktop 的 Fetch origin/Pull origin 操作 origin，不自动代表 upstream。"], commands: ["git fetch upstream", "git pull --ff-only upstream main", "git push origin main"] },
  { chapter: 9, place: "分流竹林", title: "把修复留在独立分支", story: "主角沿竹林侧路修正南门。notes.txt 是私人便条，不属于此 Issue，不能夹进提交。", objective: "创建分支、编辑 README、查看 Diff、选择暂存文件、Commit 并 Push；main 保持不变。", termIds: ["branch", "main", "working-directory", "changes", "diff", "stage", "commit", "commit-message", "sha", "push"], sourceUrl: "https://git-scm.com/docs/git-add", lastVerifiedAt: "2026-09-11", notes: ["Branch 指向开发历史。Create branch 创建，Switch branch 切换；本关创建后自动切换。", "工作区编辑不改变已有 Commit。Diff 检查新增与删除，Stage 把当时的内容放入暂存区。", "Stage 后再编辑，暂存快照不会自动更新。Uncommitted changes 是尚未提交的改动。", "Commit 保存暂存快照与说明；Push 才送到远端。c1/c2 是游戏标记，真实 SHA 是提交的对象标识。"], commands: ["git switch -c fix/south-gate", "git diff", "git add README.md", "git commit -m \"fix: correct south gate label\"", "git push -u origin fix/south-gate"] },
  { chapter: 10, place: "合卷台", title: "合卷不是直接覆盖", story: "来源分支已在你的 Fork。把来源与目标放在正确台座，邀请维护者决定是否合并。", objective: "配置 Base 与 Head/Compare，检查差异，建立 Draft PR，再标 Ready for review。", termIds: ["pull-request", "base-branch", "compare-branch", "new-pull-request", "draft", "files-changed", "conversation", "commits-tab"], sourceUrl: "https://docs.github.com/en/pull-requests/reference/pull-requests", lastVerifiedAt: "2026-09-11", notes: ["Pull Request 是合并变更提案，不是 git pull，也不是已经合并。", "Base repository/branch 是接收方；Head repository 与 Compare branch 是变更来源。跨 Fork 尤其容易选反。", "Compare changes 预览差异；Files changed 看文件改动；Commits 看提交；Conversation 看讨论。", "Draft 是草稿；Ready for review 是准备审阅，不是批准。这里向虚构上游贡献；真实毕业练习两边都选自己的 Fork。"], commands: [] },
  { chapter: 11, place: "议事堂", title: "把意见变成新提交", story: "维护者请你补一句‘夜间请结伴通行。’。独立冲突练习中，一方改入口、一方改时间，不能粗暴选一边。", objective: "读 Review、编辑并推送修订、处理讨论、请求复查；编辑冲突结果保留双方意图。", termIds: ["review", "comment", "approve", "request-changes", "resolve-conversation", "merge-conflict", "commit", "push"], sourceUrl: "https://docs.github.com/en/pull-requests/reference/pull-request-reviews", lastVerifiedAt: "2026-09-11", notes: ["Comment 讨论、Approve 批准、Request changes 请求修改，三者不是一个状态。", "Resolve conversation 标记讨论已处理，不自动修改文件或通过 Checks。先 Commit/Push 再解决讨论。", "请求复查后显示的是 NPC 模拟结果，玩家没有批准自己的真实 PR。", "Merge conflict 是 Git 无法自动组合变化；检查双方意图，编辑结果并移除冲突标记。"], commands: ["git diff", "git add README.md", "git commit -m \"docs: explain night route safety\"", "git push origin fix/south-gate"] },
  { chapter: 12, place: "百炼炉", title: "检查通过，再交付版本", story: "火炉分三站验收：文件、测试、发布说明。第一次失败不是惩罚，而是告诉你缺了哪一项。", objective: "执行三 Step、读失败日志、修复发布草稿、重跑；Checks Passed 后模拟 Merge、Release 与删分支。", termIds: ["actions", "workflow", "workflow-run", "job", "step", "checks", "passed", "failed", "merge", "release", "tag", "changelog", "artifact", "github-pages"], sourceUrl: "https://docs.github.com/en/actions/get-started/understand-github-actions", lastVerifiedAt: "2026-09-11", notes: ["Actions 是自动化功能；Workflow 是定义，Workflow run 是一次执行；Job 包含 Step。", "Checks 是检查结果。Passed 通过、Failed 失败、Cancelled 取消，取消不是通过。逐步按钮是游戏机制，真实 CI 由运行器执行。", "检查通过才能 Merge 是本教学规则，不代表所有仓库默认强制。", "Tag 标记版本位置；Release 组织发行说明和附件；Version 是版本号，Changelog 说明改了什么。Artifact 不自动等于 Release。", "GitHub Pages 托管静态网站。Squash and merge 压缩提交，Rebase and merge 重放提交；本关模拟普通 Merge。"], commands: [] },
].map(lesson => chainLessonSchema.parse(lesson));
export const contributionByChapter = (chapter: number) => contributionMissions.find(item => item.chapter === chapter)!;
