'use client';
import {useState} from 'react';
import {routePath,} from '@/core/game/campaign';
import {routeRequests,routeEntries,securityRequests,securityTargets,workshopOrders,shelfCards,shelfQuestions} from '@/content/minigames/campaign';
import {Act,Art,ObjectChoice,Select,Fact,flagged,type BoardProps} from './shared';
export function RouteBoard({b,send}:BoardProps){
 const [selected,select]=useState('');
 const requests=routeRequests(b.seed), connected=b.lists.connected??[];
 const stones=b.seed?[[2,2],[3,4],[3,1]]:[[2,1],[3,3],[2,4]];
 const point=([x,y]:number[])=>[220+x*112,35+y*103];
 const lines=connected.flatMap(id=>{const i=requests.findIndex(r=>r.id===id),j=routeEntries.indexOf(requests[i]?.entry??'');const path=b.values[`path:${id}`]?JSON.parse(b.values[`path:${id}`]) as number[][]:routePath(b.seed,i,j,connected);return path?[{id,points:path.map(p=>point(p).join(',')).join(' ')}]:[];});
 return <div className="route-board"><div className="route-field" aria-label="山道连连看">
 <svg className="route-grid-lines" viewBox="0 0 1000 600" preserveAspectRatio="none" aria-label="已接通的山道">{lines.map(line=><polyline className="route-ink-line" key={line.id} data-route={line.id} points={line.points} fill="none" stroke="#79543a" strokeWidth="3" strokeDasharray="7 5" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"/>)}</svg>
 {stones.map(([x,y])=><div className="route-stone" key={`${x}-${y}`} style={{left:`${point([x,y])[0]/10}%`,top:`${point([x,y])[1]/6}%`}}><Art chapter={0} index={2}/></div>)}
 {requests.map((r,i)=><div className="route-end request" key={r.id} style={{top:`${point([0,i+1])[1]/6}%`}}><ObjectChoice chapter={0} index={1} chosen={selected===r.id} disabled={connected.includes(r.id)} onClick={()=>select(r.id)}>{r.label}{connected.includes(r.id)&&<small>已抵达</small>}</ObjectChoice></div>)}
 {routeEntries.map((entry,i)=><div className="route-end destination" key={entry} style={{top:`${point([5,i+1])[1]/6}%`}}><ObjectChoice chapter={0} index={0} chosen={connected.some(id=>requests.find(r=>r.id===id)?.entry===entry)} onClick={()=>selected&&send({type:'connect',id:selected,target:entry})}>{entry}</ObjectChoice></div>)}
 </div><aside className="board-note"><Art chapter={0} index={4}/><h3>旅人路引</h3><p>{selected&&!connected.includes(selected)?`已选：${requests.find(r=>r.id===selected)?.label}。现在点右侧入口。`:'选一位旅人，再为他指向合适的入口。'}</p><Fact label="已经抵达" value={`${connected.length} / ${requests.length}`}/>{connected.length===requests.length?<><p>{b.seed?'带这位旅人找到 macOS 成品包。':'带贡献旅人依次读说明、取得自己的副本，再带回电脑。'}</p><div className="choice-row">{['README','自己的 Fork','Clone','Releases','macOS 附件'].map(id=><Act key={id} onClick={()=>send({type:'journey',id})}>{id}</Act>)}</div><p>已走 {b.step} / 3 步</p></>:<p>四位旅人都到达后，继续下一段路。</p>}</aside></div>;
}

export function SecurityBoard({b,send}:BoardProps){const list=securityRequests(b.seed),requests=b.seed?[...list].reverse():list;const req=requests[b.step];if(!req)return <div className="board-finish"><Art chapter={1} index={5}/><h3>全部来信已安全处置</h3></div>;return <div className="security-board"><div className="letter-stand"><Art chapter={1} index={0}/><small>第 {b.step+1} 封 / {requests.length}</small><h3>{req.title}</h3><Act onClick={()=>send({type:'inspect',id:req.id})}>展开请求与来源</Act>{flagged(b,`read:${req.id}`)&&<div className="letter-copy"><strong>{req.source}</strong><p>{req.detail}</p></div>}</div><div className="security-slots">{securityTargets.map((target,i)=><ObjectChoice key={target} chapter={1} index={i===6?3:i===5?0:2} onClick={()=>send({type:'route-request',id:req.id,target})}>{target}<small>{i===5?'秘密由本人保管':i===6?'拒绝索取，不作填写':'仅认识官方入口'}</small></ObjectChoice>)}</div></div>;}
export function WorkshopBoard({b,send}:BoardProps){const orders=workshopOrders(b.seed);const [order,setOrder]=useState('o0'),[method,setMethod]=useState('Fork'),[slot,setSlot]=useState('0');return <div className="workshop-board"><div className="order-rack">{orders.map((o,i)=><ObjectChoice key={o.id} chapter={2} index={3} disabled={b.lists.delivered?.includes(o.id)} chosen={order===o.id} onClick={()=>setOrder(o.id)}><small>订单 {i+1}</small>{o.need}</ObjectChoice>)}</div><div className="workshop-controls"><Select label="加工工艺" value={method} options={['Fork','Clone','Download ZIP','Codespaces']} onChange={setMethod}/><Select label="安排工位" value={slot} options={['0','1']} onChange={setSlot}/><Act onClick={()=>send({type:'produce',id:order,target:method,value:slot})}>安排生产</Act></div><div className="workstation-row">{['0','1'].map((slot,i)=>{const o=orders.find(o=>o.id===b.values[`station${slot}`]);return <section className="workstation" key={slot}><Art chapter={2} index={o?['Fork','Clone','Download ZIP','Codespaces'].indexOf(o.method)===3?7:i:6}/><h3>工位 {Number(slot)+1}</h3>{o?<><strong>{o.method}</strong><p>{o.owner} · {o.history}<br/>{o.relation}</p><div className="choice-row">{['自己的账号','电脑','云端'].map(target=><Act key={target} onClick={()=>send({type:'deliver',id:o.id,target})}>交到{target}</Act>)}</div></>:<p>空位，等待订单</p>}</section>;})}<aside className="board-note"><Art chapter={2} index={5}/><h3>连接方式核对</h3><p>Clone 要核对来源地址；这里只选择方式，无凭据输入。</p>{['HTTPS','SSH 公钥认证','SSH 私钥'].map(target=><Act key={target} chosen={b.values.protocol===target} onClick={()=>send({type:'protocol',target})}>{target}</Act>)}<p>已交付 {b.lists.delivered?.length??0} / 4</p></aside></div></div>;}
export function FurnaceBoard({b,send}:BoardProps){return <div className="furnace-board"><aside className="board-note"><Select label="Terminal 当前目录" value={b.values.directory} options={['Downloads','project','Documents']} onChange={target=>send({type:'directory',target})}/><Act onClick={()=>send({type:'environment',target:'Node 22 / npm'})}>核对 Node 22 / npm</Act><p>{b.values.environment}</p><ObjectChoice chapter={3} index={4} onClick={()=>send({type:'log'})}>展开 Terminal 日志</ObjectChoice>{b.values.phase==='fault'&&<Act onClick={()=>send({type:'free-port'})}>停止模拟占用进程</Act>}</aside><div className="furnace-machine"><div className="pipe-row">{['pipe0','pipe1'].map((id,i)=><button className="pipe-control" key={id} onClick={()=>send({type:'rotate',id})} aria-label={`旋转接头 ${i+1}`}><Art chapter={3} index={3} className={`rotation-${b.numbers[id]}`}/><strong>{['北','东','南','西'][b.numbers[id]]}</strong><small>目标：{i===0?'东':b.seed?'西':'南'}</small></button>)}</div><Art chapter={3} index={0} className="furnace-body"/>{flagged(b,'running')&&<Art chapter={3} index={7} className="furnace-flame"/>}<div className="choice-row"><Act onClick={()=>send({type:'install'})}>npm install</Act><Act onClick={()=>send({type:'start'})}>npm run dev</Act><Act onClick={()=>send({type:'stop'})}>停止 Ctrl+C</Act></div></div><aside className="board-note"><ObjectChoice chapter={3} index={5} onClick={()=>send({type:'visit'})}>访问 localhost</ObjectChoice><Fact label="服务" value={flagged(b,'running')?'运行中':'已停止'}/><Fact label="依赖箱" value={flagged(b,'dependencies')?'已准备':'待安装'}/><Fact label="历练" value={b.values.phase==='boot'?'初次点火':'故障修复'}/></aside></div>;}
export function ShelfBoard({b,send}:BoardProps){const tray=b.lists.tray,archived=b.lists.archived,q=shelfQuestions(b.seed)[b.step];const [answer,setAnswer]=useState('相同');return <div className="shelf-board"><div className="layered-library">{shelfCards.map((c,i)=>{const removed=tray.includes(c.id)||archived.includes(c.id);const blocked=shelfCards.some(top=>top.covers.includes(c.id)&&!tray.includes(top.id)&&!archived.includes(top.id));return <button key={c.id} className={`library-card ${blocked?'covered':''} ${removed?'removed':''}`} disabled={removed} style={{gridColumn:i%6+1,gridRow:Math.floor(i/6)+1}} onClick={()=>send({type:'take',id:c.id})} aria-label={`取册 ${c.label}${blocked?'（上层遮挡）':''}`}><Art chapter={4} index={c.asset}/><strong>{c.label}</strong><small>{removed?'已取走':blocked?'上层遮挡':'可取册'}</small></button>;})}</div><aside className="shelf-evidence"><h3>访客问证 · {Math.min(b.step+1,5)} / 5</h3><p>{q?.label??'五份证据已全部归档。'}</p><div className="four-tray">{Array.from({length:4},(_,i)=>{const c=shelfCards.find(c=>c.id===tray[i]);return <div key={i}><Art chapter={4} index={2}/>{c&&<><strong>{c.label}</strong><p>{c.detail}</p><Act onClick={()=>send({type:'return',id:c.id})}>退回</Act></>}</div>;})}</div>{q?.id==='version'&&<Select label="版本关系" value={answer} options={['相同','不同']} onChange={setAnswer}/>}<Act disabled={!q} onClick={()=>send({type:'archive',target:answer})}>用托盘证据归档</Act><p>一次放四册；不用的册页可以免费退回。</p></aside></div>;}
