'use client';
import type { CSSProperties, ReactNode } from 'react';
import type { CampaignBoard, CampaignEvent } from '@/core/game/campaign';
export type BoardProps={b:CampaignBoard;send:(event:CampaignEvent)=>void};
export function Art({chapter,index=0,className='',label}:{chapter:number;index?:number;className?:string;label?:string}){return <span role={label?'img':undefined} aria-label={label} aria-hidden={label?undefined:true} className={`campaign-art ${className}`} style={{backgroundImage:`url(/assets/phase-c/refined/ch${chapter}-${index}.png)`} as CSSProperties}/>;}
export function Act({children,onClick,disabled=false,chosen=false,className='',label}:{children:ReactNode;onClick:()=>void;disabled?:boolean;chosen?:boolean;className?:string;label?:string}){return <button type="button" className={`campaign-action ${chosen?'chosen':''} ${className}`} disabled={disabled} aria-pressed={chosen||undefined} aria-label={label} onClick={onClick}>{children}</button>;}
export function ObjectChoice({chapter,index,children,onClick,chosen=false,disabled=false,className='',label}:{chapter:number;index:number;children:ReactNode;onClick:()=>void;chosen?:boolean;disabled?:boolean;className?:string;label?:string}){return <button type="button" className={`object-choice ${chosen?'chosen':''} ${className}`} aria-label={label} aria-pressed={chosen||undefined} disabled={disabled} onClick={onClick}><Art chapter={chapter} index={index}/><span>{children}</span></button>;}
export function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label className="campaign-field">{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>;}
export function Write({label,value,onChange,placeholder='',multiline=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;multiline?:boolean}){return <label className="campaign-field">{label}{multiline?<textarea rows={3} value={value} maxLength={2500} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>:<input value={value} maxLength={200} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>}</label>;}
export function Fact({label,value}:{label:string;value:string|number}){return <div className="campaign-fact"><small>{label}</small><strong>{value}</strong></div>;}
export const flagged=(b:CampaignBoard,f:string)=>b.flags.includes(f);
