import {describe,it,expect} from 'vitest';
import {advanceInn, bestScoringIndices, newInnRun, scoreDice, innTotal} from '@/core/game/inn';
import {initialWuxia,wuxiaReducer,type WuxiaState} from '@/core/game/wuxia';
import {parseWuxiaSave} from '@/core/persistence/chapter-storage';
import {campaignSolution} from '../helpers/campaign-solutions';
function player(){let s=wuxiaReducer(initialWuxia(),{type:'hydrate',save:null});s=wuxiaReducer(s,{type:'intro'});return wuxiaReducer(s,{type:'character',id:'atuan'});}
function chapter(s:WuxiaState,ch:number){s=wuxiaReducer(s,{type:'enter',chapter:ch});for(const event of campaignSolution(ch,s.campaign[ch]?.seed??0))s=wuxiaReducer(s,{type:'campaign-act',event});expect(s.error,s.notice).toBe(false);return s;}
describe('six-dice choices and three-round settlement',()=>{
 it('scores only complete legal combinations',()=>{expect(scoreDice([1,5])).toBe(150);expect(scoreDice([2,2,2])).toBe(200);expect(scoreDice([1,1,1,1])).toBe(2000);expect(scoreDice([1,2,3,4,5,6])).toBe(1500);expect(scoreDice([2,2,3,3,6,6])).toBe(1500);expect(scoreDice([1,5,2])).toBe(0);expect(scoreDice([7])).toBe(0);expect(scoreDice([])).toBe(0);});
 it('offers scoring combinations without calling a losing hand a win',()=>{expect(bestScoringIndices([2,3,4,6])).toEqual([]);expect(bestScoringIndices([2,3,1,5])).toEqual([2,3]);});
 it('banking keeps points and a bust loses only the current unbanked pot',()=>{let r=newInnRun(1,5);r=advanceInn(r,{type:'roll',dice:[1,2,3,4,6,2]}).run;r=advanceInn(r,{type:'keep',indices:[0]}).run;r=advanceInn(r,{type:'bank'}).run;expect(r.scores).toEqual([100]);r=advanceInn(r,{type:'next'}).run;r=advanceInn(r,{type:'roll',dice:[1,2,3,4,6,2]}).run;r=advanceInn(r,{type:'keep',indices:[0]}).run;r=advanceInn(r,{type:'roll',dice:[2,2,3,4,6]}).run;expect(r.scores).toEqual([100,0]);expect(r.stage).toBe('round-end');});
 it('hot dice restore six dice; duplicate or non-scoring selection does not mutate state',()=>{let r=newInnRun(1,5);r=advanceInn(r,{type:'roll',dice:[1,2,3,4,5,6]}).run;expect(advanceInn(r,{type:'keep',indices:[0,0]}).error).toBeTruthy();expect(advanceInn(r,{type:'keep',indices:[1]}).run).toEqual(r);r=advanceInn(r,{type:'keep',indices:[0,1,2,3,4,5]}).run;expect(r.remaining).toBe(6);expect(r.pot).toBe(1500);expect(advanceInn(r,{type:'roll',dice:[0,1,2,3,4,5]}).error).toBeTruthy();});
 it('locks paid entry but allows a complete free practice without balance or high-score changes',()=>{let s=player();expect(wuxiaReducer(s,{type:'inn-start',stake:5}).error).toBe(true);s=wuxiaReducer(s,{type:'inn-start',stake:0});s=wuxiaReducer(s,{type:'inn-act',event:{type:'abandon'}});expect(s.inn.active?.stage).toBe('finished');expect(s.inn.plays).toBe(0);expect(s.wallet.copper).toBe(0);expect(parseWuxiaSave(s)).not.toBeNull();});
 it('full paid run reloads mid-turn and settles exactly once; silver buys persistent decor',()=>{let s=player();for(let ch=0;ch<5;ch++)s=chapter(s,ch);expect(s.wallet.silver).toBe(1);s=wuxiaReducer(s,{type:'inn-decor'});expect(s.inn.decor).toBe(true);expect(s.wallet.silver).toBe(0);s=wuxiaReducer(s,{type:'inn-start',stake:10});expect(s.wallet.copper).toBe(40);
 for(let i=0;i<3;i++){s=wuxiaReducer(s,{type:'inn-act',event:{type:'roll',dice:[1,1,1,2,3,4]}});s=wuxiaReducer(s,{type:'inn-act',event:{type:'keep',indices:[0,1,2]}});const loaded=parseWuxiaSave(s)!;expect(loaded).not.toBeNull();s={...s,...loaded};s=wuxiaReducer(s,{type:'inn-act',event:{type:'bank'}});if(i<2)s=wuxiaReducer(s,{type:'inn-act',event:{type:'next'}});}
 expect(innTotal(s.inn.active!)).toBe(3000);expect(s.wallet.copper).toBe(60);expect(s.inn.bestScore).toBe(3000);expect(s.inn.plays).toBe(1);const again=wuxiaReducer(s,{type:'inn-act',event:{type:'bank'}});expect(again.wallet).toEqual(s.wallet);expect(parseWuxiaSave(s)).not.toBeNull();});
 it('fresh mainline replays pay four copper, undo cannot duplicate reward, and three notes are real purchases',()=>{let s=player();for(let ch=0;ch<5;ch++){s=chapter(s,ch);if([1,2,3].includes(ch)){s=wuxiaReducer(s,{type:'buy-hint'});const duplicate=wuxiaReducer(s,{type:'buy-hint'});expect(duplicate.wallet).toEqual(s.wallet);}}
 expect(s.wallet.copper).toBe(35);s=wuxiaReducer(s,{type:'enter',chapter:0});s=wuxiaReducer(s,{type:'campaign-restart'});s=chapter(s,0);expect(s.wallet.copper).toBe(39);s=wuxiaReducer(s,{type:'campaign-undo'});s=wuxiaReducer(s,{type:'campaign-act',event:campaignSolution(0).at(-1)!});expect(s.wallet.copper).toBe(39);expect(parseWuxiaSave(s)).not.toBeNull();});
 it('old saves migrate with zero new inn scores and preserved wallet',()=>{const s=player();const {inn,...old}=s;void inn;const migrated=parseWuxiaSave({...old,sidequest:{plays:99,bestScore:9999,titles:['旧称号']}})!;expect(migrated.inn.bestScore).toBe(0);expect(migrated.sidequest.bestScore).toBe(9999);expect(migrated.wallet.copper).toBe(0);});
});
