import type {CampaignEvent} from '@/core/game/campaign';
import {routeRequests,securityRequests,workshopOrders,issueFragments,changeSlips} from '@/content/minigames/campaign';
export function campaignSolution(ch:number,seed=0):CampaignEvent[]{const e=(type:string,id?:string,target?:string,value?:string):CampaignEvent=>({type,...id?{id}:{},...target?{target}:{},...value!==undefined?{value}:{}});switch(ch){
case 0:return [...routeRequests(seed).map(r=>e('connect',r.id,r.entry)),...(seed?['README','Releases','macOS 附件']:['README','自己的 Fork','Clone']).map(id=>e('journey',id))];
case 1:{const req=securityRequests(seed);return (seed?req.reverse():req).flatMap(r=>[e('inspect',r.id),e('route-request',r.id,r.target)]);}
case 2:return [e('protocol',undefined,seed?'SSH 公钥认证':'HTTPS'),...workshopOrders(seed).flatMap(o=>[e('produce',o.id,o.method,'0'),e('deliver',o.id,o.station)])];
case 3:return [e('log'),e('directory',undefined,'project'),e('environment',undefined,'Node 22 / npm'),e('rotate','pipe0'),...Array.from({length:seed?3:2},()=>e('rotate','pipe1')),e('install'),e('start'),e('visit'),e('stop'),e('log'),seed?e('free-port'):e('install'),e('start'),e('visit'),e('stop')];
case 4:return ['readme','license','public'].map(id=>e('take',id)).concat(e('archive'),e('return','readme'),...['branch','files'].map(id=>e('take',id)),e('archive'),...['history','owner'].map(id=>e('take',id)),e('archive'),...['release','tag'].map(id=>e('take',id)),e('archive',undefined,'不同'),...['private','archive'].map(id=>e('take',id)),e('archive'));
case 5:return [e('wager',undefined,undefined,'0'),e('search',undefined,'TypeScript / map'),...['req','license','docs','maintenance'].map(f=>e('investigate',seed?'cloud':'reed',f)),e('dispute',undefined,'Stars 不等于适配'),e('conclude',seed?'cloud':'reed')];
case 6:return [e('rule',undefined,seed?'all':'release'),e('launch'),...['Star','Watch','Follow','Fork','收件箱',seed?'收件箱':'静音归档','收件箱',seed?'收件箱':'静音归档','Issue','Discussions',seed?'收件箱':'静音归档','收件箱'].map((t,i)=>e('sort',`m${i}`,t))];
case 7:return [...['Contributing','Code of conduct','Security policy'].map(id=>e('charter',id)),...issueFragments(seed).slice(0,3).map(f=>e('fragment',f.id,f.slot)),e('case-route','duplicate','关联已有 Issue'),e('case-route','security','私下 Security policy'),e('assign','Label','bug'),e('assign','Assignee',seed?'知微':'青砚'),e('assign','Milestone',seed?'修桥计划':'夜行图修订'),e('assign','Subscribe','跟进'),e('submit'),e('comment',undefined,undefined,'按上述复现步骤已经观察到同样错误'),e('mention',undefined,seed?'知微':'青砚'),e('repair'),e('close')];
case 8:return [e('alias','upstream','原项目'),e('alias','origin','自己的 Fork'),e('fetch'),e('pull'),e('push',undefined,'origin'),e('note',undefined,'留在本地，先 Commit'),e('receipt')];
case 9:return [e('create',undefined,seed?'m1':'m0','fix/south-gate'),...(seed?[e('clear-note')]:[]),e('switch'),e('edit',undefined,undefined,seed?'从东桥进入':'从南门进入'),e('review-diff',undefined,seed?'西桥 → 东桥':'北门 → 南门')];
case 10:return [...changeSlips(seed).filter(s=>s.related).flatMap(s=>[e('take',s.id),e('stage',s.id)]),e('edit-again'),e('stage','readme'),e('commit',undefined,undefined,'修复 README 南门入口说明'),e('push',undefined,'origin'),e('receipt',undefined,undefined,`模拟 c${seed+1}`)];
case 11:return [e('direction','base','自己的 Fork / main'),e('direction','head','自己的 Fork / fix'),e('files'),e('draft'),e('ready'),e('revise',undefined,undefined,seed?'东桥夜间结伴':'南门夜间结伴'),e('push'),e('resolve'),e('approve'),e('conflict',undefined,undefined,seed?'东桥于 18:00 开放，夜间结伴':'南门于 18:00 开放，夜间结伴'),e('push'),e('approve'),e('merge')];
case 12:return [e('dependency','build','check'),e('dependency','deliver','build'),e('run'),e('tick'),e('log'),e('repair',undefined,undefined,`${seed?'needs: check；':''}修复南门入口说明，夜间结伴安全通行`),e('commit'),e('push'),e('rerun'),e('tick'),e('run'),e('cancel'),e('rerun'),e('tick'),e('tick'),e('tick'),e('tag',undefined,'c2','v1.0.1'),e('release',undefined,'nightwalk-c2.zip','本版修复南门入口，保留夜间结伴及开放时间说明'),e('pages',undefined,'静态展示')];
default:throw Error('Unknown chapter');}}
